from installer.ui.screens.welcome import WelcomeScreen
from installer.ui.screens.language import LanguageScreen
from installer.ui.screens.keyboard import KeyboardScreen
from installer.ui.screens.partition import PartitionScreen
from installer.ui.screens.base import BaseSystemScreen
from installer.ui.screens.bootloader import BootloaderScreen
from installer.ui.screens.user import UserScreen
from installer.ui.screens.desktop import DesktopScreen
from installer.ui.screens.summary import SummaryScreen
from installer.ui.screens.installation import InstallationScreen